#ifndef __MESSAGES_H__
#define __MESSAGES_H__

#include <stdarg.h>

#ifdef __cplusplus
extern "C" {
#endif

/*

This is a list of messages generated by PropLoader.  There are two command line options that affect the message output; -c and -v (code and verbose, respectively).
By default (ie: when no -c or -v option is active) a limited set of messages appears and contain just the text of the message.

With -c, a numeric code is prepended to each message in the format ###-<text_message>.
With -v, verbose (debugging) messages appear along with normal messages.  These are messages meant only for PropLoader developers to diagnose problems.
Both -c and -v can be used individually or together.

There are three categories of messages and message codes:

  * Status - These express state/progress/event information and are given codes 001 through 099.

  * Error - These express fatal problems and are given codes 100 and beyond.

  * Verbose - These are for seasoned developers. They may express state information or specific deep error information that is usually only helpful to a small
    set of users, thus, they are never shown without an active -v option on the command line. These are all automatically given the code 000; tools that parse
    them should ignore all 000-coded messages.

Code numbers ARE NEVER REUSED for a condition that means something different than what was first intended by a message.  When a new State or Error message
is created, it simply takes on the next available code number even if it's logically related to another far away message.

*/

enum {
    /* 000 */ DEBUG_MESSAGE,

    MIN_INFO                                        = 1,
    /* 001 */ INFO_OPENING_FILE                     = MIN_INFO,
    /* 002 */ INFO_DOWNLOADING,
    /* 003 */ INFO_VERIFYING_RAM,
    /* 004 */ INFO_PROGRAMMING_EEPROM,
    /* 005 */ INFO_DOWNLOAD_SUCCESSFUL,
    /* 006 */ INFO_TERMINAL_MODE,
    /* 007 */ INFO_WRITING_TO_SD_CARD,
    /* 008 */ INFO_BYTES_REMAINING,
    /* 009 */ INFO_BYTES_SENT,
    /* 010 */ INFO_SETTING_MODULE_NAME,
    /* 011 */ INFO_USING_ALTERNATE_PORT,
    MAX_INFO,
    
    MIN_ERROR                                       = 100,
    /* 100 */ ERROR_CAN_ONLY_NAME_WIFI_MODULES      = MIN_ERROR,
    /* 101 */ ERROR_INVALID_MODULE_ADDRESS,
    /* 102 */ ERROR_DOWNLOAD_FAILED,
    /* 103 */ ERROR_CANT_OPEN_FILE,
    /* 104 */ ERROR_PROPELLER_NOT_FOUND,
    /* 105 */ ERROR_FAILED_TO_ENTER_TERMINAL_MODE,
    /* 106 */ ERROR_WRONG_WIFI_MODULE_FIRMWARE,
    /* 107 */ ERROR_FAILED_TO_WRITE_TO_SD_CARD,
    /* 108 */ ERROR_INVALID_MODULE_NAME,
    /* 109 */ ERROR_FAILED_TO_SET_MODULE_NAME,
    /* 110 */ ERROR_FILE_TRUNCATED,
    /* 111 */ ERROR_FILE_CORRUPTED,
    /* 112 */ ERROR_CANT_READ_PROPELLER_APP_FILE,
    /* 113 */ ERROR_WIFI_MODULE_DISCOVERY_FAILED,
    /* 114 */ ERROR_NO_WIFI_MODULES_FOUND,
    /* 115 */ ERROR_SERIAL_PORT_DISCOVERY_FAILED,
    /* 116 */ ERROR_NO_SERIAL_PORTS_FOUND,
    /* 117 */ ERROR_UNABLE_TO_CONNECT_TO_PORT,
    /* 118 */ ERROR_UNABLE_TO_CONNECT_TO_MODULE,
    /* 119 */ ERROR_FAILED_TO_SET_BAUD_RATE,
    /* 120 */ ERROR_INTERNAL_CODE_ERROR,
    /* 121 */ ERROR_INSUFFICIENT_MEMORY,
    /* 122 */ ERROR_NO_RESET_METHOD,
    /* 123 */ ERROR_RESET_FAILED,
    /* 124 */ ERROR_WRONG_PROPELLER_VERSION,
    MAX_ERROR
};

extern int showMessageCodes;
extern int verbose;

int error(const char *fmt, ...);
int nerror(int code, ...);
void message(const char *fmt, ...);
void nmessage(int code, ...);
void nprogress(int code, ...);

#ifdef __cplusplus
}
#endif

#endif
