#ifndef __MESSAGES_H__
#define __MESSAGES_H__

#include <stdarg.h>

#ifdef __cplusplus
extern "C" {
#endif

/*

This is a list of messages generated by PropLoader.  There are two command line options that affect the message output; -c and -v (code and verbose, respectively).
By default (ie: when no -c or -v option is active) a limited set of messages appears and contain just the text of the message.

With -c, a numeric code is prepended to each message in the format ###-<text_message>.
With -v, verbose (debugging) messages appear along with normal messages.  These are messages meant only for PropLoader developers to diagnose problems.
Both -c and -v can be used individually or together.

There are three categories of messages and message codes:

  * Status - These express state/progress/event information and are given codes 001 through 099.

  * Error - These express fatal problems and are given codes 100 and beyond.

  * Verbose - These are for seasoned developers. They may express state information or specific deep error information that is usually only helpful to a small
    set of users, thus, they are never shown without an active -v option on the command line. These are all automatically given the code 000; tools that parse
    them should ignore all 000-coded messages.

Code numbers ARE NEVER REUSED for a condition that means something different than what was first intended by a message.  When a new State or Error message
is created, it simply takes on the next available code number even if it's logically related to another far away message.

*/

enum {
    MIN_INFO                            = 1,
    INFO_OPENING_FILE                   = MIN_INFO,
    INFO_DOWNLOADING,
    INFO_VERIFYING_RAM,
    INFO_PROGRAMMING_EEPROM,
    INFO_DOWNLOAD_SUCCESSFUL,
    INFO_TERMINAL_MODE,
    INFO_WRITING_TO_SD_CARD,
    INFO_BYTES_REMAINING,
    INFO_BYTES_SENT,
    INFO_SETTING_MODULE_NAME,
    MAX_INFO,
    
    MIN_ERROR                           = 100,
    ERROR_CAN_ONLY_NAME_WIFI_MODULES    = MIN_ERROR,
    ERROR_INVALID_MODULE_ADDRESS,
    ERROR_DOWNLOAD_FAILED,
    ERROR_CANT_OPEN_FILE,
    ERROR_PROPELLER_NOT_FOUND,
    ERROR_FAILED_TO_ENTER_TERMINAL_MODE,
    ERROR_WRONG_WIFI_MODULE_FIRMWARE,
    ERROR_FAILED_TO_WRITE_TO_SD_CARD,
    ERROR_INVALID_MODULE_NAME,
    ERROR_FAILED_TO_SET_MODULE_NAME,
    ERROR_FILE_TRUNCATED,
    ERROR_FILE_CORRUPTED,
    ERROR_CANT_READ_PROPELLER_APP_FILE,
    ERROR_WIFI_MODULE_DISCOVERY_FAILED,
    ERROR_NO_WIFI_MODULES_FOUND,
    ERROR_SERIAL_PORT_DISCOVERY_FAILED,
    ERROR_NO_SERIAL_PORTS_FOUND,
    ERROR_UNABLE_TO_CONNECT_TO_PORT,
    ERROR_UNABLE_TO_CONNECT_TO_MODULE,
    ERROR_FAILED_TO_SET_BAUD_RATE,
    ERROR_INTERNAL_CODE_ERROR,
    ERROR_INSUFFICIENT_MEMORY,
    MAX_ERROR
};

extern int showMessageCodes;
extern int verbose;

int error(const char *fmt, ...);
int nerror(int code, ...);
void message(const char *fmt, ...);
void nmessage(int code, ...);
void progress(const char *fmt, ...);

#ifdef __cplusplus
}
#endif

#endif
